# Generated by Django 5.1.6 on 2025-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_groupmessage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userkey",
            name="public_key",
            field=models.JSONField(),
        ),
    ]
