version: '3.9'

services:

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend-dev.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid overwriting node_modules
    ports:
      - "5173:5173"  # Expose Vite's dev server
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host


volumes:
  postgres_data: